name: dart_package_boilerplate
version: 0.1.0
description: Dart Package Boilerplate
homepage: https://github.com/vaetas/dart_package_boilerplate

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
